/* The following code was generated by JFlex 1.4.3 on 5/09/21 22:13 */

package com.alexsantos.proyecto01.analyzer.javascript;
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 5/09/21 22:13 from the specification file
 * <tt>/home/alex/Documentos/USAC/Compi1/proyecto01/proyecto01/src/main/java/com/alexsantos/proyecto01/analyzer/javascript/scanner.lex</tt>
 */
public class JSScanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\12\1\13\1\0\1\12\1\14\22\0\1\12\1\35\1\7"+
    "\2\0\1\31\1\33\1\7\1\23\1\24\1\11\1\27\1\15\1\30"+
    "\1\3\1\10\12\1\1\16\1\20\1\36\1\17\1\37\2\0\1\42"+
    "\1\60\1\40\1\57\1\46\1\53\1\62\1\56\1\54\1\2\1\61"+
    "\1\41\1\2\1\51\1\50\1\2\1\63\1\45\1\43\1\47\1\52"+
    "\1\44\1\55\3\2\1\25\1\0\1\26\1\34\1\4\1\0\1\42"+
    "\1\60\1\40\1\57\1\46\1\53\1\62\1\56\1\54\1\2\1\61"+
    "\1\41\1\2\1\51\1\50\1\2\1\63\1\45\1\43\1\47\1\52"+
    "\1\44\1\55\3\2\1\21\1\32\1\22\123\0\1\2\37\0\1\2"+
    "\u1f2a\0\1\5\1\6\udfe2\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\2\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\2\1\1\25"+
    "\1\26\1\27\1\30\14\3\1\2\1\0\1\31\1\7"+
    "\1\0\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\14\3\1\47"+
    "\2\3\1\50\1\3\1\0\2\51\1\0\3\3\1\52"+
    "\1\53\1\3\1\54\4\3\1\55\3\3\1\56\1\3"+
    "\1\57\3\3\1\60\1\61\4\3\1\62\1\63\3\3"+
    "\1\64\1\65\1\3\1\66\1\3\1\67\2\3\1\70"+
    "\1\71\1\72";

  private static int [] zzUnpackAction() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\64\0\320\0\u0104\0\u0138"+
    "\0\u016c\0\u01a0\0\64\0\64\0\64\0\64\0\64\0\64"+
    "\0\64\0\64\0\64\0\64\0\u01d4\0\u0208\0\u023c\0\u0270"+
    "\0\u02a4\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410"+
    "\0\u0444\0\u0478\0\u04ac\0\u04e0\0\u0514\0\u0548\0\u057c\0\u05b0"+
    "\0\u05e4\0\u0618\0\u0104\0\64\0\u064c\0\u0680\0\64\0\64"+
    "\0\64\0\64\0\64\0\64\0\64\0\64\0\64\0\64"+
    "\0\64\0\64\0\64\0\u06b4\0\u06e8\0\u071c\0\u0750\0\u0784"+
    "\0\u07b8\0\u07ec\0\u0820\0\u0854\0\u0888\0\u08bc\0\u08f0\0\234"+
    "\0\u0924\0\u0958\0\234\0\u098c\0\u064c\0\64\0\u064c\0\u09c0"+
    "\0\u09f4\0\u0a28\0\u0a5c\0\234\0\234\0\u0a90\0\234\0\u0ac4"+
    "\0\u0af8\0\u0b2c\0\u0b60\0\234\0\u0b94\0\u0bc8\0\u0bfc\0\64"+
    "\0\u0c30\0\234\0\u0c64\0\u0c98\0\u0ccc\0\234\0\234\0\u0d00"+
    "\0\u0d34\0\u0d68\0\u0d9c\0\234\0\234\0\u0dd0\0\u0e04\0\u0e38"+
    "\0\234\0\234\0\u0e6c\0\234\0\u0ea0\0\234\0\u0ed4\0\u0f08"+
    "\0\234\0\234\0\234";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\2\1\7"+
    "\1\10\1\11\3\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\4\1\40\1\41\1\42\1\43\1\44\3\4\1\45"+
    "\1\46\1\47\1\4\1\50\1\51\3\4\65\0\1\3"+
    "\1\0\1\52\61\0\2\4\1\0\1\4\33\0\24\4"+
    "\2\0\1\4\35\0\24\4\6\53\2\54\3\53\1\54"+
    "\50\53\10\0\1\55\1\56\5\0\1\57\63\0\1\60"+
    "\56\0\3\12\66\0\1\61\7\0\1\62\53\0\1\63"+
    "\10\0\1\64\52\0\1\65\76\0\1\66\64\0\1\67"+
    "\47\0\1\70\63\0\1\71\63\0\1\72\63\0\1\73"+
    "\45\0\2\4\1\0\1\4\33\0\1\4\1\74\1\75"+
    "\5\4\1\76\13\4\1\0\2\4\1\0\1\4\33\0"+
    "\6\4\1\77\1\4\1\100\13\4\1\0\2\4\1\0"+
    "\1\4\33\0\15\4\1\101\6\4\1\0\2\4\1\0"+
    "\1\4\33\0\2\4\1\102\21\4\1\0\2\4\1\0"+
    "\1\4\33\0\6\4\1\103\15\4\1\0\2\4\1\0"+
    "\1\4\33\0\1\4\1\104\22\4\1\0\2\4\1\0"+
    "\1\4\33\0\5\4\1\105\16\4\1\0\2\4\1\0"+
    "\1\4\33\0\2\4\1\106\5\4\1\107\13\4\1\0"+
    "\2\4\1\0\1\4\33\0\13\4\1\110\10\4\1\0"+
    "\2\4\1\0\1\4\33\0\16\4\1\111\5\4\1\0"+
    "\2\4\1\0\1\4\33\0\6\4\1\112\1\4\1\113"+
    "\13\4\1\0\2\4\1\0\1\4\33\0\5\4\1\114"+
    "\16\4\1\0\1\52\62\0\13\115\1\116\1\117\47\115"+
    "\11\56\1\120\52\56\1\0\2\4\1\0\1\4\33\0"+
    "\2\4\1\121\21\4\1\0\2\4\1\0\1\4\33\0"+
    "\3\4\1\122\20\4\1\0\2\4\1\0\1\4\33\0"+
    "\11\4\1\123\12\4\1\0\2\4\1\0\1\4\33\0"+
    "\7\4\1\124\14\4\1\0\2\4\1\0\1\4\33\0"+
    "\22\4\1\125\1\4\1\0\2\4\1\0\1\4\33\0"+
    "\14\4\1\126\7\4\1\0\2\4\1\0\1\4\33\0"+
    "\5\4\1\127\16\4\1\0\2\4\1\0\1\4\33\0"+
    "\23\4\1\130\1\0\2\4\1\0\1\4\33\0\3\4"+
    "\1\131\20\4\1\0\2\4\1\0\1\4\33\0\12\4"+
    "\1\132\11\4\1\0\2\4\1\0\1\4\33\0\1\4"+
    "\1\133\22\4\1\0\2\4\1\0\1\4\33\0\5\4"+
    "\1\134\16\4\1\0\2\4\1\0\1\4\33\0\14\4"+
    "\1\135\7\4\1\0\2\4\1\0\1\4\33\0\13\4"+
    "\1\136\10\4\1\0\2\4\1\0\1\4\33\0\6\4"+
    "\1\137\15\4\10\0\1\140\54\0\2\4\1\0\1\4"+
    "\33\0\3\4\1\141\20\4\1\0\2\4\1\0\1\4"+
    "\33\0\6\4\1\142\15\4\1\0\2\4\1\0\1\4"+
    "\33\0\3\4\1\143\20\4\1\0\2\4\1\0\1\4"+
    "\33\0\7\4\1\144\14\4\1\0\2\4\1\0\1\4"+
    "\33\0\12\4\1\145\11\4\1\0\2\4\1\0\1\4"+
    "\33\0\6\4\1\146\15\4\1\0\2\4\1\0\1\4"+
    "\33\0\6\4\1\147\15\4\1\0\2\4\1\0\1\4"+
    "\33\0\3\4\1\150\20\4\1\0\2\4\1\0\1\4"+
    "\33\0\1\4\1\151\22\4\1\0\2\4\1\0\1\4"+
    "\33\0\2\4\1\152\21\4\1\0\2\4\1\0\1\4"+
    "\33\0\2\4\1\153\21\4\1\0\2\4\1\0\1\4"+
    "\33\0\3\4\1\154\20\4\1\0\2\4\1\0\1\4"+
    "\33\0\7\4\1\155\1\156\13\4\1\0\2\4\1\0"+
    "\1\4\33\0\1\157\23\4\1\0\2\4\1\0\1\4"+
    "\33\0\14\4\1\160\7\4\1\0\2\4\1\0\1\4"+
    "\33\0\6\4\1\161\15\4\1\0\2\4\1\0\1\4"+
    "\33\0\6\4\1\162\15\4\1\0\2\4\1\0\1\4"+
    "\33\0\12\4\1\163\11\4\1\0\2\4\1\0\1\4"+
    "\33\0\21\4\1\164\2\4\1\0\2\4\1\0\1\4"+
    "\33\0\1\4\1\165\22\4\1\0\2\4\1\0\1\4"+
    "\33\0\16\4\1\166\5\4\1\0\2\4\1\0\1\4"+
    "\33\0\5\4\1\167\16\4\1\0\2\4\1\0\1\4"+
    "\33\0\1\4\1\170\22\4\1\0\2\4\1\0\1\4"+
    "\33\0\6\4\1\171\15\4\1\0\2\4\1\0\1\4"+
    "\33\0\6\4\1\172\15\4\1\0\2\4\1\0\1\4"+
    "\33\0\7\4\1\173\14\4";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3900];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\5\1\12\11\26\1\1\0"+
    "\1\11\1\1\1\0\15\11\21\1\1\0\1\11\1\1"+
    "\1\0\17\1\1\11\33\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[123];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public JSScanner(java.io.Reader in) {
      yyline = 1;
    yycolumn = 1;
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public JSScanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 188) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 45: 
          { return new Symbol(sym.forsym,yycolumn,yyline,yytext());
          }
        case 59: break;
        case 8: 
          { return new Symbol(sym.comma,yycolumn,yyline,yytext());
          }
        case 60: break;
        case 25: 
          { return new Symbol(sym.strtext,yyline,yycolumn, yytext());
          }
        case 61: break;
        case 5: 
          { return new Symbol(sym.div,yycolumn,yyline,yytext());
          }
        case 62: break;
        case 19: 
          { return new Symbol(sym.lessM,yycolumn,yyline,yytext());
          }
        case 63: break;
        case 35: 
          { return new Symbol(sym.xoreq,yycolumn,yyline,yytext());
          }
        case 64: break;
        case 44: 
          { return new Symbol(sym.var,yycolumn,yyline,yytext());
          }
        case 65: break;
        case 11: 
          { return new Symbol(sym.semicolom,yycolumn,yyline,yytext());
          }
        case 66: break;
        case 34: 
          { return new Symbol(sym.and,yycolumn,yyline,yytext());
          }
        case 67: break;
        case 9: 
          { return new Symbol(sym.colom,yycolumn,yyline,yytext());
          }
        case 68: break;
        case 22: 
          { return new Symbol(sym.not,yycolumn,yyline,yytext());
          }
        case 69: break;
        case 15: 
          { return new Symbol(sym.closeparenthesis,yycolumn,yyline,yytext());
          }
        case 70: break;
        case 33: 
          { return new Symbol(sym.or,yycolumn,yyline,yytext());
          }
        case 71: break;
        case 41: 
          { return new Symbol(sym.mcmt,yyline,yycolumn, yytext());
          }
        case 72: break;
        case 38: 
          { return new Symbol(sym.lessoreq,yycolumn,yyline,yytext());
          }
        case 73: break;
        case 16: 
          { return new Symbol(sym.opensquarebracket,yycolumn,yyline,yytext());
          }
        case 74: break;
        case 57: 
          { return new Symbol(sym.requiresym,yycolumn,yyline,yytext());
          }
        case 75: break;
        case 43: 
          { return new Symbol(sym.logsym,yycolumn,yyline,yytext());
          }
        case 76: break;
        case 21: 
          { return new Symbol(sym.xor,yycolumn,yyline,yytext());
          }
        case 77: break;
        case 10: 
          { return new Symbol(sym.equals,yycolumn,yyline,yytext());
          }
        case 78: break;
        case 20: 
          { return new Symbol(sym.mod,yycolumn,yyline,yytext());
          }
        case 79: break;
        case 48: 
          { return new Symbol(sym.elsesym,yycolumn,yyline,yytext());
          }
        case 80: break;
        case 2: 
          { return new Symbol(sym.decimal,yyline,yycolumn, yytext());
          }
        case 81: break;
        case 55: 
          { return new Symbol(sym.switchsym,yycolumn,yyline,yytext());
          }
        case 82: break;
        case 51: 
          { return new Symbol(sym.constsym,yycolumn,yyline,yytext());
          }
        case 83: break;
        case 17: 
          { return new Symbol(sym.closesquarebracket,yycolumn,yyline,yytext());
          }
        case 84: break;
        case 18: 
          { return new Symbol(sym.plus,yycolumn,yyline,yytext());
          }
        case 85: break;
        case 32: 
          { return new Symbol(sym.modeq,yycolumn,yyline,yytext());
          }
        case 86: break;
        case 4: 
          { return new Symbol(sym.dot,yycolumn,yyline,yytext());
          }
        case 87: break;
        case 30: 
          { return new Symbol(sym.lesseq,yycolumn,yyline,yytext());
          }
        case 88: break;
        case 24: 
          { return new Symbol(sym.major,yycolumn,yyline,yytext());
          }
        case 89: break;
        case 1: 
          { System.err.println("\nError lexico en la linea " + yyline +
        " columna " + yycolumn + " componente: " + yytext() + ".\n");
          }
        case 90: break;
        case 28: 
          { return new Symbol(sym.pluseq,yycolumn,yyline,yytext());
          }
        case 91: break;
        case 12: 
          { return new Symbol(sym.openbracket,yycolumn,yyline,yytext());
          }
        case 92: break;
        case 49: 
          { return new Symbol(sym.booltrue,yycolumn,yyline,yytext());
          }
        case 93: break;
        case 50: 
          { return new Symbol(sym.classsym,yycolumn,yyline,yytext());
          }
        case 94: break;
        case 26: 
          { return new Symbol(sym.diveq,yycolumn,yyline,yytext());
          }
        case 95: break;
        case 23: 
          { return new Symbol(sym.minor,yycolumn,yyline,yytext());
          }
        case 96: break;
        case 14: 
          { return new Symbol(sym.openparenthesis,yycolumn,yyline,yytext());
          }
        case 97: break;
        case 42: 
          { return new Symbol(sym.let,yycolumn,yyline,yytext());
          }
        case 98: break;
        case 31: 
          { return new Symbol(sym.lessMlessM,yycolumn,yyline,yytext());
          }
        case 99: break;
        case 6: 
          { return new Symbol(sym.times,yycolumn,yyline,yytext());
          }
        case 100: break;
        case 27: 
          { return new Symbol(sym.timeseq,yycolumn,yyline,yytext());
          }
        case 101: break;
        case 54: 
          { return new Symbol(sym.breaksym,yycolumn,yyline,yytext());
          }
        case 102: break;
        case 52: 
          { return new Symbol(sym.boolfalse,yycolumn,yyline,yytext());
          }
        case 103: break;
        case 37: 
          { return new Symbol(sym.moreoreq,yycolumn,yyline,yytext());
          }
        case 104: break;
        case 53: 
          { return new Symbol(sym.whilesym,yycolumn,yyline,yytext());
          }
        case 105: break;
        case 40: 
          { return new Symbol(sym.dosym,yycolumn,yyline,yytext());
          }
        case 106: break;
        case 36: 
          { return new Symbol(sym.notequals,yycolumn,yyline,yytext());
          }
        case 107: break;
        case 13: 
          { return new Symbol(sym.closebracket,yycolumn,yyline,yytext());
          }
        case 108: break;
        case 46: 
          { return new Symbol(sym.cmt,yyline,yycolumn, yytext());
          }
        case 109: break;
        case 58: 
          { return new Symbol(sym.defaultsym,yycolumn,yyline,yytext());
          }
        case 110: break;
        case 3: 
          { return new Symbol(sym.id,yycolumn,yyline,yytext());
          }
        case 111: break;
        case 47: 
          { return new Symbol(sym.casesym,yycolumn,yyline,yytext());
          }
        case 112: break;
        case 39: 
          { return new Symbol(sym.ifsym,yycolumn,yyline,yytext());
          }
        case 113: break;
        case 56: 
          { return new Symbol(sym.console,yycolumn,yyline,yytext());
          }
        case 114: break;
        case 7: 
          { 
          }
        case 115: break;
        case 29: 
          { return new Symbol(sym.plusplus,yycolumn,yyline,yytext());
          }
        case 116: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
