
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 05 22:13:10 CST 2021
//----------------------------------------------------

package com.alexsantos.proyecto01.analyzer.javascript;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int modeq = 30;
  public static final int function = 43;
  public static final int elsesym = 47;
  public static final int plusplus = 37;
  public static final int closeparenthesis = 13;
  public static final int closebracket = 10;
  public static final int switchsym = 51;
  public static final int plus = 17;
  public static final int mod = 21;
  public static final int forsym = 48;
  public static final int minor = 33;
  public static final int ifsym = 46;
  public static final int moreoreq = 34;
  public static final int dosym = 50;
  public static final int boolfalse = 45;
  public static final int lessM = 18;
  public static final int comma = 7;
  public static final int major = 32;
  public static final int let = 41;
  public static final int requiresym = 58;
  public static final int casesym = 53;
  public static final int notequals = 36;
  public static final int xoreq = 28;
  public static final int console = 55;
  public static final int var = 40;
  public static final int mcmt = 6;
  public static final int EOF = 0;
  public static final int strtext = 3;
  public static final int openparenthesis = 12;
  public static final int breaksym = 54;
  public static final int defaultsym = 52;
  public static final int error = 1;
  public static final int equals = 8;
  public static final int times = 19;
  public static final int or = 22;
  public static final int colom = 14;
  public static final int timeseq = 27;
  public static final int xor = 24;
  public static final int id = 4;
  public static final int logsym = 57;
  public static final int whilesym = 49;
  public static final int lessMlessM = 38;
  public static final int cmt = 5;
  public static final int lessoreq = 35;
  public static final int pluseq = 25;
  public static final int and = 23;
  public static final int not = 31;
  public static final int booltrue = 44;
  public static final int lesseq = 26;
  public static final int classsym = 39;
  public static final int div = 20;
  public static final int diveq = 29;
  public static final int opensquarebracket = 15;
  public static final int semicolom = 11;
  public static final int decimal = 2;
  public static final int dot = 56;
  public static final int constsym = 42;
  public static final int openbracket = 9;
  public static final int closesquarebracket = 16;
}

