
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 12 04:02:49 CST 2021
//----------------------------------------------------

package com.alexsantos.proyecto01.analyzer.javascript;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int modeq = 29;
  public static final int elsesym = 45;
  public static final int plusplus = 36;
  public static final int closeparenthesis = 14;
  public static final int closebracket = 11;
  public static final int switchsym = 49;
  public static final int plus = 16;
  public static final int mod = 20;
  public static final int forsym = 46;
  public static final int minor = 32;
  public static final int ifsym = 44;
  public static final int moreoreq = 33;
  public static final int dosym = 48;
  public static final int boolfalse = 43;
  public static final int lessM = 17;
  public static final int comma = 7;
  public static final int major = 31;
  public static final int let = 40;
  public static final int requiresym = 56;
  public static final int casesym = 51;
  public static final int notequals = 35;
  public static final int xoreq = 27;
  public static final int console = 53;
  public static final int var = 39;
  public static final int mcmt = 6;
  public static final int EOF = 0;
  public static final int timestimes = 10;
  public static final int strtext = 3;
  public static final int openparenthesis = 13;
  public static final int breaksym = 52;
  public static final int defaultsym = 50;
  public static final int error = 1;
  public static final int equals = 8;
  public static final int times = 18;
  public static final int or = 21;
  public static final int colom = 15;
  public static final int timeseq = 26;
  public static final int xor = 23;
  public static final int id = 4;
  public static final int logsym = 55;
  public static final int whilesym = 47;
  public static final int lessMlessM = 37;
  public static final int cmt = 5;
  public static final int lessoreq = 34;
  public static final int pluseq = 24;
  public static final int and = 22;
  public static final int not = 30;
  public static final int booltrue = 42;
  public static final int lesseq = 25;
  public static final int classsym = 38;
  public static final int div = 19;
  public static final int diveq = 28;
  public static final int semicolom = 12;
  public static final int decimal = 2;
  public static final int dot = 54;
  public static final int constsym = 41;
  public static final int openbracket = 9;
}

