
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 11 02:01:32 CST 2021
//----------------------------------------------------

package com.alexsantos.proyecto01.analyzer.javascript;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int modeq = 28;
  public static final int elsesym = 44;
  public static final int plusplus = 35;
  public static final int closeparenthesis = 13;
  public static final int closebracket = 10;
  public static final int switchsym = 48;
  public static final int plus = 15;
  public static final int mod = 19;
  public static final int forsym = 45;
  public static final int minor = 31;
  public static final int ifsym = 43;
  public static final int moreoreq = 32;
  public static final int dosym = 47;
  public static final int boolfalse = 42;
  public static final int lessM = 16;
  public static final int comma = 7;
  public static final int major = 30;
  public static final int let = 39;
  public static final int requiresym = 55;
  public static final int casesym = 50;
  public static final int xoreq = 26;
  public static final int notequals = 34;
  public static final int console = 52;
  public static final int var = 38;
  public static final int mcmt = 6;
  public static final int EOF = 0;
  public static final int strtext = 3;
  public static final int openparenthesis = 12;
  public static final int breaksym = 51;
  public static final int defaultsym = 49;
  public static final int error = 1;
  public static final int equals = 8;
  public static final int times = 17;
  public static final int or = 20;
  public static final int colom = 14;
  public static final int timeseq = 25;
  public static final int xor = 22;
  public static final int id = 4;
  public static final int logsym = 54;
  public static final int whilesym = 46;
  public static final int lessMlessM = 36;
  public static final int cmt = 5;
  public static final int lessoreq = 33;
  public static final int pluseq = 23;
  public static final int and = 21;
  public static final int not = 29;
  public static final int booltrue = 41;
  public static final int lesseq = 24;
  public static final int classsym = 37;
  public static final int div = 18;
  public static final int diveq = 27;
  public static final int semicolom = 11;
  public static final int decimal = 2;
  public static final int dot = 53;
  public static final int constsym = 40;
  public static final int openbracket = 9;
}

