
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 23 16:56:57 CST 2021
//----------------------------------------------------

package com.alexsantos.proyecto01.analyzer.fca;

import java_cup.runtime.*;
import java.util.ArrayList;
import com.alexsantos.proyecto01.graphs.*;
import com.alexsantos.proyecto01.utils.Tools;
import com.alexsantos.proyecto01.fca.Reports;
import com.alexsantos.proyecto01.controllers.Primary;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon Aug 23 16:56:57 CST 2021
  */
public class FCAParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public FCAParser() {super();}

  /** Constructor which sets the default scanner. */
  public FCAParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public FCAParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\064\000\002\002\004\000\002\015\005\000\002\015" +
    "\005\000\002\015\003\000\002\015\003\000\002\016\005" +
    "\000\002\016\005\000\002\016\003\000\002\016\003\000" +
    "\002\002\003\000\002\003\006\000\002\010\004\000\002" +
    "\010\003\000\002\010\003\000\002\010\004\000\002\011" +
    "\003\000\002\011\003\000\002\011\003\000\002\011\004" +
    "\000\002\004\010\000\002\005\006\000\002\006\005\000" +
    "\002\006\004\000\002\007\006\000\002\007\006\000\002" +
    "\020\003\000\002\020\003\000\002\020\003\000\002\017" +
    "\005\000\002\017\005\000\002\021\007\000\002\022\007" +
    "\000\002\014\006\000\002\030\005\000\002\030\004\000" +
    "\002\031\003\000\002\031\003\000\002\032\005\000\002" +
    "\032\005\000\002\013\006\000\002\027\005\000\002\027" +
    "\004\000\002\012\006\000\002\023\005\000\002\023\004" +
    "\000\002\024\003\000\002\024\003\000\002\024\003\000" +
    "\002\025\005\000\002\025\005\000\002\026\005\000\002" +
    "\026\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\153\000\004\011\004\001\002\000\004\021\010\001" +
    "\002\000\004\002\ufff8\001\002\000\004\002\007\001\002" +
    "\000\004\002\001\001\002\000\014\012\013\013\014\014" +
    "\024\015\020\016\015\001\002\000\016\012\ufff1\013\ufff1" +
    "\014\ufff1\015\ufff1\016\ufff1\022\ufff1\001\002\000\016\012" +
    "\ufff2\013\ufff2\014\ufff2\015\ufff2\016\ufff2\022\ufff2\001\002" +
    "\000\004\024\151\001\002\000\004\021\132\001\002\000" +
    "\004\021\115\001\002\000\004\023\114\001\002\000\016" +
    "\012\013\013\014\014\024\015\020\016\015\022\ufff4\001" +
    "\002\000\004\021\104\001\002\000\016\012\013\013\014" +
    "\014\024\015\020\016\015\022\ufff5\001\002\000\016\012" +
    "\ufff0\013\ufff0\014\ufff0\015\ufff0\016\ufff0\022\ufff0\001\002" +
    "\000\004\022\102\001\002\000\004\021\025\001\002\000" +
    "\014\031\034\032\035\033\036\035\032\036\031\001\002" +
    "\000\016\022\100\031\034\032\035\033\036\035\032\036" +
    "\031\001\002\000\004\023\uffd4\001\002\000\004\023\076" +
    "\001\002\000\004\026\073\001\002\000\004\026\070\001" +
    "\002\000\004\023\uffe6\001\002\000\004\026\065\001\002" +
    "\000\004\026\054\001\002\000\004\026\043\001\002\000" +
    "\004\023\uffd2\001\002\000\004\023\uffe8\001\002\000\004" +
    "\023\uffd3\001\002\000\004\023\uffe7\001\002\000\004\027" +
    "\044\001\002\000\006\004\045\006\047\001\002\000\006" +
    "\017\ufffa\030\ufffa\001\002\000\006\017\050\030\051\001" +
    "\002\000\006\017\ufff9\030\ufff9\001\002\000\006\004\052" +
    "\006\053\001\002\000\004\023\uffe2\001\002\000\006\017" +
    "\ufffc\030\ufffc\001\002\000\006\017\ufffb\030\ufffb\001\002" +
    "\000\004\027\055\001\002\000\006\005\056\006\060\001" +
    "\002\000\006\017\ufffe\030\ufffe\001\002\000\006\017\061" +
    "\030\062\001\002\000\006\017\ufffd\030\ufffd\001\002\000" +
    "\006\005\063\006\064\001\002\000\004\023\uffe3\001\002" +
    "\000\006\017\000\030\000\001\002\000\006\017\uffff\030" +
    "\uffff\001\002\000\006\005\066\006\067\001\002\000\004" +
    "\023\uffe5\001\002\000\004\023\uffe4\001\002\000\006\005" +
    "\071\006\072\001\002\000\004\023\uffd1\001\002\000\004" +
    "\023\uffd0\001\002\000\006\005\074\006\075\001\002\000" +
    "\004\023\uffcf\001\002\000\004\023\uffce\001\002\000\016" +
    "\022\uffd5\031\uffd5\032\uffd5\033\uffd5\035\uffd5\036\uffd5\001" +
    "\002\000\004\023\101\001\002\000\016\012\uffd7\013\uffd7" +
    "\014\uffd7\015\uffd7\016\uffd7\022\uffd7\001\002\000\016\022" +
    "\uffd6\031\uffd6\032\uffd6\033\uffd6\035\uffd6\036\uffd6\001\002" +
    "\000\004\002\ufff7\001\002\000\004\022\ufff6\001\002\000" +
    "\010\031\034\032\035\033\036\001\002\000\012\022\110" +
    "\031\034\032\035\033\036\001\002\000\004\023\107\001" +
    "\002\000\012\022\uffd8\031\uffd8\032\uffd8\033\uffd8\001\002" +
    "\000\016\012\uffda\013\uffda\014\uffda\015\uffda\016\uffda\022" +
    "\uffda\001\002\000\004\023\112\001\002\000\012\022\uffd9" +
    "\031\uffd9\032\uffd9\033\uffd9\001\002\000\004\022\ufff3\001" +
    "\002\000\016\012\uffef\013\uffef\014\uffef\015\uffef\016\uffef" +
    "\022\uffef\001\002\000\006\031\034\034\120\001\002\000" +
    "\010\022\127\031\034\034\120\001\002\000\004\023\uffdd" +
    "\001\002\000\004\026\124\001\002\000\004\023\123\001" +
    "\002\000\004\023\uffde\001\002\000\010\022\uffdf\031\uffdf" +
    "\034\uffdf\001\002\000\006\005\125\006\126\001\002\000" +
    "\004\023\uffdc\001\002\000\004\023\uffdb\001\002\000\016" +
    "\012\uffe1\013\uffe1\014\uffe1\015\uffe1\016\uffe1\022\uffe1\001" +
    "\002\000\004\023\131\001\002\000\010\022\uffe0\031\uffe0" +
    "\034\uffe0\001\002\000\006\007\136\010\135\001\002\000" +
    "\010\007\136\010\135\022\146\001\002\000\004\023\145" +
    "\001\002\000\004\006\142\001\002\000\004\006\137\001" +
    "\002\000\004\020\140\001\002\000\004\005\141\001\002" +
    "\000\004\023\uffea\001\002\000\004\020\143\001\002\000" +
    "\004\004\144\001\002\000\004\023\uffe9\001\002\000\010" +
    "\007\uffeb\010\uffeb\022\uffeb\001\002\000\016\012\uffed\013" +
    "\uffed\014\uffed\015\uffed\016\uffed\022\uffed\001\002\000\004" +
    "\023\150\001\002\000\010\007\uffec\010\uffec\022\uffec\001" +
    "\002\000\004\005\152\001\002\000\004\017\153\001\002" +
    "\000\004\005\154\001\002\000\004\025\155\001\002\000" +
    "\004\023\uffee\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\153\000\006\002\005\003\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\004\015\005\016\010\022\011\020\012\011\013" +
    "\010\014\021\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\020\004\015\005\016\010\112\011\020" +
    "\012\011\013\010\014\021\001\001\000\002\001\001\000" +
    "\020\004\015\005\016\010\102\011\020\012\011\013\010" +
    "\014\021\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\022\017\037\020\026\021\041\022\032" +
    "\023\025\024\027\025\040\026\036\001\001\000\020\017" +
    "\037\020\026\021\041\022\032\024\076\025\040\026\036" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\016\045\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\015\056\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\014\017\037\020\105\021\041\022" +
    "\032\027\104\001\001\000\012\017\037\020\110\021\041" +
    "\022\032\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\017\121\030\115\031" +
    "\120\032\116\001\001\000\010\017\121\031\127\032\116" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\006\132\007\133" +
    "\001\001\000\004\007\146\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$FCAParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$FCAParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$FCAParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(Symbol s){
        Primary.print("Error Sintáctico en la Línea " + s.right +
        " Columna " + s.left + ". Componente: " + s.value + ".");

    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        Primary.print("Error síntactico irrecuperable en la Línea " +
        s.right + " Columna " + s.left + ". Componente: " + s.value +
        " no reconocido.");
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$FCAParser$actions {
  private final FCAParser parser;

  /** Constructor */
  CUP$FCAParser$actions(FCAParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$FCAParser$do_action(
    int                        CUP$FCAParser$act_num,
    java_cup.runtime.lr_parser CUP$FCAParser$parser,
    java.util.Stack            CUP$FCAParser$stack,
    int                        CUP$FCAParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$FCAParser$result;

      /* select the action based on the action number */
      switch (CUP$FCAParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // BARGRAPHPTITLEY ::= bgtitley colom id 
            {
              String RESULT =null;
		int tIdleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int tIdright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String tId = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    Reports reports = Reports.getInstance();
    RESULT = (String) reports.getGlobalProp(tId);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("BARGRAPHPTITLEY",20, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // BARGRAPHPTITLEY ::= bgtitley colom strtext 
            {
              String RESULT =null;
		int textleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int textright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    RESULT = Tools.trimStr(text);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("BARGRAPHPTITLEY",20, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // BARGRAPHPTITLEX ::= bgtitlex colom id 
            {
              String RESULT =null;
		int tIdleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int tIdright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String tId = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    Reports reports = Reports.getInstance();
    RESULT = (String) reports.getGlobalProp(tId);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("BARGRAPHPTITLEX",19, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // BARGRAPHPTITLEX ::= bgtitlex colom strtext 
            {
              String RESULT =null;
		int textleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int textright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    RESULT = Tools.trimStr(text);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("BARGRAPHPTITLEX",19, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // BARGRAPHPROP ::= BARGRAPHPTITLEY 
            {
              Object[] RESULT =null;
		int propleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int propright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String prop = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    RESULT = new Object[] {prop, "yaxisTitle", propright};

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("BARGRAPHPROP",18, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // BARGRAPHPROP ::= BARGRAPHPTITLEX 
            {
              Object[] RESULT =null;
		int propleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int propright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String prop = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    RESULT = new Object[] {prop, "xaxisTitle", propright};

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("BARGRAPHPROP",18, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // BARGRAPHPROP ::= GRAPHPROP 
            {
              Object[] RESULT =null;
		int propleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int propright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		Object[] prop = (Object[])((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    RESULT = prop;

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("BARGRAPHPROP",18, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // BARGRAPHPROPS ::= BARGRAPHPROP semicolom 
            {
              BarGraph RESULT =null;
		int propleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).left;
		int propright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).right;
		Object[] prop = (Object[])((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).value;
		
    BarGraph barGraph = new BarGraph();
    RESULT = barGraph;
    RESULT.setProp(prop);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("BARGRAPHPROPS",17, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // BARGRAPHPROPS ::= BARGRAPHPROPS BARGRAPHPROP semicolom 
            {
              BarGraph RESULT =null;
		int graphleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).left;
		int graphright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).right;
		BarGraph graph = (BarGraph)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).value;
		int propleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).left;
		int propright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).right;
		Object[] prop = (Object[])((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).value;
		
    RESULT = graph;
    RESULT.setProp(prop);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("BARGRAPHPROPS",17, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // BARGRAPH ::= bargraph openbracket BARGRAPHPROPS closebracket 
            {
              Object RESULT =null;
		int graphleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).left;
		int graphright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).right;
		BarGraph graph = (BarGraph)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).value;
		
    Reports reports = Reports.getInstance();
    reports.graphs.add(graph);
    Primary.print("Agregando grafica de barras: " + graph.title);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("BARGRAPH",8, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-3)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // PIEGRAPHPROPS ::= GRAPHPROP semicolom 
            {
              PieGraph RESULT =null;
		int propleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).left;
		int propright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).right;
		Object[] prop = (Object[])((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).value;
		
    PieGraph pieGraph = new PieGraph();
    RESULT = pieGraph;
    RESULT.setProp(prop);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("PIEGRAPHPROPS",21, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // PIEGRAPHPROPS ::= PIEGRAPHPROPS GRAPHPROP semicolom 
            {
              PieGraph RESULT =null;
		int graphleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).left;
		int graphright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).right;
		PieGraph graph = (PieGraph)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).value;
		int propleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).left;
		int propright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).right;
		Object[] prop = (Object[])((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).value;
		
    RESULT = graph;
    RESULT.setProp(prop);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("PIEGRAPHPROPS",21, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // PIEGRAPH ::= piegraph openbracket PIEGRAPHPROPS closebracket 
            {
              Object RESULT =null;
		int graphleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).left;
		int graphright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).right;
		PieGraph graph = (PieGraph)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).value;
		
    Reports reports = Reports.getInstance();
    reports.graphs.add(graph);
    Primary.print("Agregando grafica de pie: " + graph.title);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("PIEGRAPH",9, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-3)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // LINEGRAPHFILE ::= file colom id 
            {
              String RESULT =null;
		int tIdleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int tIdright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String tId = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    Reports reports = Reports.getInstance();
    RESULT = (String) reports.getGlobalProp(tId);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("LINEGRAPHFILE",24, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // LINEGRAPHFILE ::= file colom strtext 
            {
              String RESULT =null;
		int textleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int textright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    RESULT = Tools.trimStr(text);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("LINEGRAPHFILE",24, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // LINEGRAPHPROP ::= LINEGRAPHFILE 
            {
              Object[] RESULT =null;
		int textleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int textright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    RESULT = new Object[] {text, "file", textright};

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("LINEGRAPHPROP",23, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // LINEGRAPHPROP ::= GRAPHTITLE 
            {
              Object[] RESULT =null;
		int textleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int textright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    RESULT = new Object[] {text, "title", textright};

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("LINEGRAPHPROP",23, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // LINEGRAPHPROPS ::= LINEGRAPHPROP semicolom 
            {
              LineGraph RESULT =null;
		int propleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).left;
		int propright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).right;
		Object[] prop = (Object[])((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).value;
		
    LineGraph lineGraph = new LineGraph();
    RESULT = lineGraph;
    RESULT.setProp(prop);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("LINEGRAPHPROPS",22, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // LINEGRAPHPROPS ::= LINEGRAPHPROPS LINEGRAPHPROP semicolom 
            {
              LineGraph RESULT =null;
		int graphleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).left;
		int graphright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).right;
		LineGraph graph = (LineGraph)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).value;
		int propleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).left;
		int propright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).right;
		Object[] prop = (Object[])((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).value;
		
    RESULT = graph;
    RESULT.setProp(prop);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("LINEGRAPHPROPS",22, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // LINEGRAPH ::= linegraph openbracket LINEGRAPHPROPS closebracket 
            {
              Object RESULT =null;
		int graphleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).left;
		int graphright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).right;
		LineGraph graph = (LineGraph)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).value;
		
    Reports reports = Reports.getInstance();
    reports.graphs.add(graph);
    Primary.print("Agregando grafica de lineas: " + graph.title);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("LINEGRAPH",10, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-3)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // GRAPHVALUES ::= values colom opensquarebracket DOUBLELIST closesquarebracket 
            {
              ArrayList<Double> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).right;
		ArrayList<Double> list = (ArrayList<Double>)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).value;
		
    RESULT = list;

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("GRAPHVALUES",16, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-4)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // GRAPHXAXIS ::= xaxis colom opensquarebracket STRINGLIST closesquarebracket 
            {
              ArrayList<String> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).right;
		ArrayList<String> list = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).value;
		
    RESULT = list;

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("GRAPHXAXIS",15, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-4)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // GRAPHTITLE ::= title colom id 
            {
              String RESULT =null;
		int tIdleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int tIdright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String tId = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    Reports reports = Reports.getInstance();
    RESULT = (String) reports.getGlobalProp(tId);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("GRAPHTITLE",13, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // GRAPHTITLE ::= title colom strtext 
            {
              String RESULT =null;
		int textleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int textright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    RESULT = Tools.trimStr(text);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("GRAPHTITLE",13, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // GRAPHPROP ::= GRAPHVALUES 
            {
              Object[] RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		ArrayList<Double> list = (ArrayList<Double>)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    RESULT = new Object[] {list, "values", listright};

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("GRAPHPROP",14, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // GRAPHPROP ::= GRAPHXAXIS 
            {
              Object[] RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		ArrayList<String> list = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    RESULT = new Object[] {list, "xaxis", listright};

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("GRAPHPROP",14, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // GRAPHPROP ::= GRAPHTITLE 
            {
              Object[] RESULT =null;
		int titleleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int titleright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String title = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    RESULT = new Object[] {title, "title", titleright};

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("GRAPHPROP",14, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // DECLARATION ::= doubletype id equals decimal 
            {
              Object RESULT =null;
		int idstrleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).left;
		int idstrright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).right;
		String idstr = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).value;
		int textleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int textright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    Reports reports = Reports.getInstance();
    reports.setGlobalProp(idstr, Double.parseDouble(text));
    Primary.print("Declarando variable " + idstr);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("DECLARATION",5, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-3)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // DECLARATION ::= strtype id equals strtext 
            {
              Object RESULT =null;
		int idstrleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).left;
		int idstrright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).right;
		String idstr = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).value;
		int textleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int textright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    Reports reports = Reports.getInstance();
    reports.setGlobalProp(idstr, Tools.trimStr(text));
    Primary.print("Declarando variable " + idstr);

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("DECLARATION",5, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-3)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // DECLARATIONS ::= DECLARATION semicolom 
            {
              Object RESULT =null;
		 
              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("DECLARATIONS",4, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // DECLARATIONS ::= DECLARATIONS DECLARATION semicolom 
            {
              Object RESULT =null;

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("DECLARATIONS",4, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // SETGLOBALS ::= setglobals openbracket DECLARATIONS closebracket 
            {
              Object RESULT =null;
		 
              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("SETGLOBALS",3, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-3)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // COMPARE ::= compare openparenthesis strtext comma strtext closeparenthesis 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-5)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-5)).value;
		int path1left = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-3)).left;
		int path1right = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-3)).right;
		String path1 = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-3)).value;
		int path2left = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).left;
		int path2right = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).right;
		String path2 = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).value;
		
    Reports reports = Reports.getInstance();
    reports.setComparePaths(Tools.trimStr(path1), Tools.trimStr(path2), idright);
    Primary.print("Comparando proyectos " + Tools.trimStr(path1) + " y " + Tools.trimStr(path2));

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("COMPARE",2, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-5)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // FUNCTION ::= COMPARE semicolom 
            {
              Object RESULT =null;
		 
              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("FUNCTION",7, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // FUNCTION ::= LINEGRAPH 
            {
              Object RESULT =null;

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("FUNCTION",7, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // FUNCTION ::= PIEGRAPH 
            {
              Object RESULT =null;

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("FUNCTION",7, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // FUNCTION ::= BARGRAPH 
            {
              Object RESULT =null;

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("FUNCTION",7, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // FUNCTIONS ::= SETGLOBALS FUNCTIONS 
            {
              Object RESULT =null;
		 
              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("FUNCTIONS",6, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // FUNCTIONS ::= SETGLOBALS 
            {
              Object RESULT =null;

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("FUNCTIONS",6, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // FUNCTIONS ::= FUNCTION 
            {
              Object RESULT =null;

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("FUNCTIONS",6, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // FUNCTIONS ::= FUNCTION FUNCTIONS 
            {
              Object RESULT =null;

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("FUNCTIONS",6, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // MAIN ::= main openbracket FUNCTIONS closebracket 
            {
              Object RESULT =null;
		 
              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("MAIN",1, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-3)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // START ::= MAIN 
            {
              Object RESULT =null;
		
    Reports reports = Reports.getInstance();
    Primary.print("Generando todas las graficas");
    reports.generateGraphs();
    Primary.print("Fin de analisis lexico");

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("START",0, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // DOUBLELIST ::= id 
            {
              ArrayList<Double> RESULT =null;
		int textleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int textright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    Reports reports = Reports.getInstance();
    ArrayList<Double> newList = new ArrayList<Double>();
    RESULT = newList;
    RESULT.add((Double) reports.getGlobalProp(text));

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("DOUBLELIST",12, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // DOUBLELIST ::= decimal 
            {
              ArrayList<Double> RESULT =null;
		int textleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int textright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    ArrayList<Double> newList = new ArrayList<Double>();
    RESULT = newList;
    RESULT.add(Double.parseDouble(text));

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("DOUBLELIST",12, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // DOUBLELIST ::= DOUBLELIST comma id 
            {
              ArrayList<Double> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).right;
		ArrayList<Double> list = (ArrayList<Double>)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).value;
		int textleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int textright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    RESULT = list;
    Reports reports = Reports.getInstance();
    RESULT.add((Double) reports.getGlobalProp(text));

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("DOUBLELIST",12, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // DOUBLELIST ::= DOUBLELIST comma decimal 
            {
              ArrayList<Double> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).right;
		ArrayList<Double> list = (ArrayList<Double>)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).value;
		int textleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int textright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    RESULT = list;
    RESULT.add(Double.parseDouble(text));

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("DOUBLELIST",12, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // STRINGLIST ::= id 
            {
              ArrayList<String> RESULT =null;
		int textleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int textright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    Reports reports = Reports.getInstance();
    ArrayList<String> newList = new ArrayList<String>();
    RESULT = newList;
    RESULT.add((String) reports.getGlobalProp(text));

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("STRINGLIST",11, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // STRINGLIST ::= strtext 
            {
              ArrayList<String> RESULT =null;
		int textleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int textright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    ArrayList<String> newList = new ArrayList<String>();
    RESULT = newList;
    RESULT.add(Tools.trimStr(text));

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("STRINGLIST",11, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // STRINGLIST ::= STRINGLIST comma id 
            {
              ArrayList<String> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).right;
		ArrayList<String> list = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).value;
		int textleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int textright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    RESULT = list;
    Reports reports = Reports.getInstance();
    RESULT.add((String) reports.getGlobalProp(text));

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("STRINGLIST",11, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // STRINGLIST ::= STRINGLIST comma strtext 
            {
              ArrayList<String> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).right;
		ArrayList<String> list = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)).value;
		int textleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).left;
		int textright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$FCAParser$stack.peek()).value;
		
    RESULT = list;
    RESULT.add(Tools.trimStr(text));

              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("STRINGLIST",11, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-2)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          return CUP$FCAParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= START EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)).value;
		RESULT = start_val;
              CUP$FCAParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$FCAParser$stack.elementAt(CUP$FCAParser$top-1)), ((java_cup.runtime.Symbol)CUP$FCAParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$FCAParser$parser.done_parsing();
          return CUP$FCAParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

