
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 22 17:07:28 CST 2021
//----------------------------------------------------

package com.alexsantos.proyecto01.analyzer.fca;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int number = 8;
  public static final int minor = 15;
  public static final int decimal = 9;
  public static final int not = 17;
  public static final int openparenthesis = 25;
  public static final int setglobals = 4;
  public static final int main = 2;
  public static final int closebracket = 23;
  public static final int strtype = 6;
  public static final int semicolom = 24;
  public static final int times = 21;
  public static final int equals = 16;
  public static final int sharp = 12;
  public static final int div = 20;
  public static final int EOF = 0;
  public static final int id = 11;
  public static final int doubletype = 7;
  public static final int less = 19;
  public static final int strtext = 10;
  public static final int major = 14;
  public static final int error = 1;
  public static final int closeparenthesis = 26;
  public static final int bargraph = 5;
  public static final int plus = 18;
  public static final int comma = 13;
  public static final int openbracket = 22;
  public static final int compare = 3;
}

