
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 23 15:17:15 CST 2021
//----------------------------------------------------

package com.alexsantos.proyecto01.analyzer.fca;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int closeparenthesis = 27;
  public static final int closebracket = 24;
  public static final int plus = 19;
  public static final int main = 2;
  public static final int minor = 16;
  public static final int setglobals = 4;
  public static final int compare = 3;
  public static final int comma = 14;
  public static final int major = 15;
  public static final int bargraph = 5;
  public static final int EOF = 0;
  public static final int strtext = 11;
  public static final int openparenthesis = 26;
  public static final int error = 1;
  public static final int equals = 17;
  public static final int doubletype = 8;
  public static final int times = 22;
  public static final int colom = 28;
  public static final int sharp = 13;
  public static final int xaxis = 32;
  public static final int title = 31;
  public static final int id = 12;
  public static final int not = 18;
  public static final int piegraph = 6;
  public static final int less = 20;
  public static final int div = 21;
  public static final int bgtitley = 35;
  public static final int opensquarebracket = 29;
  public static final int bgtitlex = 34;
  public static final int semicolom = 25;
  public static final int strtype = 7;
  public static final int decimal = 10;
  public static final int values = 33;
  public static final int openbracket = 23;
  public static final int closesquarebracket = 30;
  public static final int number = 9;
}

