
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Aug 25 09:26:31 CST 2021
//----------------------------------------------------

package com.alexsantos.proyecto01.analyzer.fca;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int values = 25;
  public static final int decimal = 2;
  public static final int bgtitley = 28;
  public static final int xaxis = 24;
  public static final int bgtitlex = 27;
  public static final int openparenthesis = 18;
  public static final int linegraph = 12;
  public static final int setglobals = 9;
  public static final int main = 7;
  public static final int closesquarebracket = 22;
  public static final int closebracket = 16;
  public static final int strtype = 5;
  public static final int opensquarebracket = 21;
  public static final int semicolom = 17;
  public static final int equals = 14;
  public static final int EOF = 0;
  public static final int piegraph = 11;
  public static final int id = 4;
  public static final int doubletype = 6;
  public static final int strtext = 3;
  public static final int error = 1;
  public static final int closeparenthesis = 19;
  public static final int bargraph = 10;
  public static final int colom = 20;
  public static final int file = 26;
  public static final int comma = 13;
  public static final int openbracket = 15;
  public static final int compare = 8;
  public static final int title = 23;
}

